### ISSUE TITLE
MedSAM evaluation

### ISSUE THREAD

**Issue by JunMa11** [hding2455/CaRTS#17]
Hi @hding2455 ,

Thanks for adding MedSAM to the evaluation.

MedSAM is a bounding box-based segmentation method. could you please let me know how you run MedSAM?

Best regards,
Jun

**Comment by hding2455** [comment]
Hi Dr. Ma, thanks for pointing this out. I just asked the students running the experiment. All settings are the same for all models, meaning the MedSAM used the point prompts. We will run a box-prompt-based version and update the table once finished. Thank you again for pointing this out.

**Comment by JunMa11** [comment]
Hi @hding2455 ,

Thanks for your swift response. This makes sense. MedSAM was not trained with point prompts.

**Comment by hding2455** [comment]
Thanks for the information, I'll update you once we get the bounding box prompt out

**Comment by hding2455** [comment]
We've updated the box prompt results.
